export const centrosMedicos = [
    {
        name: "Centro Médico Bahía Blanca",
        address: "Calle 19 de Mayo 2345, Bahía Blanca, Buenos Aires",
        earth: "https://www.google.com/maps?q=Calle+19+de+Mayo+2345,+Bahía+Blanca,+Buenos+Aires",
        email: "bahiablanca@rollinghealth.com.ar",
        phone: "+54 291 890-1234",
        img: "/images/centrosmedicos/centro1.png",
        specialty: [
            "Cardiología",
            "Clínica Médica - Medicina Interna",
            "Dermatología",
            "Endocrinología",
            "Gastroenterología y Endoscopías",
            "Guardia Médica",
            "Laboratorio",
            "Neurología",
            "Odontología",
            "Oncología",
            "Traumatología y Ortopedia"
        ]
    },
    {
        name: "Centro Médico Capital Bienestar",
        address: "Av. Santa Fe 1010, Buenos Aires, Capital Federal",
        earth: "https://www.google.com/maps?q=Av.+Santa+Fe+1010,+Buenos+Aires,+Capital+Federal",
        email: "capital@rollinghealth.com.ar",
        phone: "+54 11 4567-8901",
        img: "/images/centrosmedicos/centro2.jpg",
        specialty: [
            "Alergia e Inmunología",
            "Cardiología",
            "Cirugía General",
            "Consultorios Externos",
            "Dermatología",
            "Diagnóstico por Imágenes",
            "Ecografía y Ecodoppler",
            "Endocrinología",
            "Ginecología",
            "Infectología",
            "Reumatología",
            "Traumatología y Ortopedia"
        ]
    },
    {
        name: "Centro Médico Chaco Salud",
        address: "Av. Sarmiento 7890, Resistencia, Chaco",
        earth: "https://www.google.com/maps?q=Av.+Sarmiento+7890,+Resistencia,+Chaco",
        email: "chaco@rollinghealth.com.ar",
        phone: "+54 362 345-6789",
        img: "/images/centrosmedicos/centro3.jpg",
        specialty: [
            "Clínica Médica - Medicina Interna",
            "Dermatología",
            "Diabetología",
            "Diagnóstico por Imágenes",
            "Gastroenterología y Endoscopías",
            "Guardia Médica",
            "Hematología",
            "Hemoterapia",
            "Infectología",
            "Nefrología",
            "Odontología",
            "Oftalmología Clínica y Quirúrgica",
            "Oncología",
            "Urología"
        ]
    },
    {
        name: "Centro Médico Córdoba Vida",
        address: "Calle Obispo Trejo 456, Córdoba, Córdoba",
        earth: "https://www.google.com/maps?q=Calle+Obispo+Trejo+456,+Córdoba,+Córdoba",
        email: "cordoba@rollinghealth.com.ar",
        phone: "+54 351 234-5678",
        img: "/images/centrosmedicos/centro4.jpg",
        specialty: [
            "Alergia e Inmunología",
            "Cardiología",
            "Cirugía",
            "Clínica Médica - Medicina Interna",
            "Cuidados Intensivos",
            "Dermatología",
            "Endocrinología",
            "Ginecología",
            "Laboratorio",
            "Neurología",
            "Oftalmología Clínica y Quirúrgica",
            "Salud Mental",
            "Traumatología y Ortopedia",
            "Urología"
        ]
    },
    {
        name: "Centro Médico Formosa Vida",
        address: "Calle Rivadavia 8901, Formosa, Formosa",
        earth: "https://www.google.com/maps?q=Calle+Rivadavia+8901,+Formosa,+Formosa",
        email: "formosa@rollinghealth.com.ar",
        phone: "+54 370 456-7890",
        img: "/images/centrosmedicos/centro5.jpg",
        specialty: [
            "Cardiología",
            "Cirugía General",
            "Clínica Médica - Medicina Interna",
            "Dermatología",
            "Ecografía y Ecodoppler",
            "Gastroenterología y Endoscopías",
            "Guardia Médica",
            "Infectología",
            "Neurología",
            "Odontología",
            "Oftalmología Clínica y Quirúrgica",
            "Otorrinolaringología",
            "Traumatología y Ortopedia"
        ]
    },
    {
        name: "Centro Médico Jujuy Bienestar",
        address: "Calle Alvear 6789, San Salvador de Jujuy, Jujuy",
        earth: "https://www.google.com/maps?q=Calle+Alvear+6789,+San+Salvador+de+Jujuy,+Jujuy",
        email: "jujuy@rollinghealth.com.ar",
        phone: "+54 388 234-5678",
        img: "/images/centrosmedicos/centro6.jpg",
        specialty: [
            "Alergia e Inmunología",
            "Cardiología",
            "Cirugía General",
            "Consultorios Externos",
            "Dermatología",
            "Diagnóstico por Imágenes",
            "Gastroenterología y Endoscopías",
            "Guardia Médica",
            "Infectología",
            "Nefrología",
            "Neurología",
            "Odontología",
            "Rehabilitación",
            "Salud Mental"
        ]
    },
    {
        name: "Centro Médico La Plata",
        address: "Calle 12 1234, La Plata, Buenos Aires",
        earth: "https://www.google.com/maps?q=Calle+12+1234,+La+Plata,+Buenos+Aires",
        email: "laplata@rollinghealth.com.ar",
        phone: "+54 221 678-9012",
        img: "/images/centrosmedicos/centro7.jpg",
        specialty: [
            "Alergia e Inmunología",
            "Cirugía Plástica",
            "Consultorios Externos",
            "Cuidados Paliativos",
            "Dermatología",
            "Diagnóstico por Imágenes",
            "Ecografía y Ecodoppler",
            "Endocrinología",
            "Gastroenterología y Endoscopías",
            "Ginecología",
            "Hemoterapia",
            "Hospital de Día",
            "Infectología",
            "Microbiología"
        ]
    },
    {
        name: "Centro Médico Mar del Plata",
        address: "Av. Colón 5678, Mar del Plata, Buenos Aires",
        earth: "https://www.google.com/maps?q=Av.+Colón+5678,+Mar+del+Plata,+Buenos+Aires",
        email: "mardelplata@rollinghealth.com.ar",
        phone: "+54 223 789-0123",
        img: "/images/centrosmedicos/centro8.jpg",
        specialty: [
            "Cardiología",
            "Cirugía General",
            "Dermatología",
            "Diagnóstico por Imágenes",
            "Gastroenterología y Endoscopías",
            "Guardia Médica",
            "Hematología",
            "Laboratorio",
            "Neumonología",
            "Odontología",
            "Oncología",
            "Otorrinolaringología",
            "Salud Mental",
            "Urología"
        ]
    },
    {
        name: "Centro Médico Mendoza Salud",
        address: "Calle San Martín 1111, Mendoza, Mendoza",
        earth: "https://www.google.com/maps?q=Calle+San+Martín+1111,+Mendoza,+Mendoza",
        email: "mendoza@rollinghealth.com.ar",
        phone: "+54 261 567-8901",
        img: "/images/centrosmedicos/centro9.jpg",
        specialty: [
            "Alergia e Inmunología",
            "Cardiología",
            "Clínica Médica - Medicina Interna",
            "Dermatología",
            "Diabetología",
            "Endocrinología",
            "Gastroenterología y Endoscopías",
            "Guardia Médica",
            "Hematología",
            "Nefrología",
            "Neurología",
            "Oncología",
            "Reumatología",
            "Traumatología y Ortopedia",
            "Urología"
        ]
    },
    {
        name: "Centro Médico Neuquén Salud",
        address: "Calle San Juan 3456, Neuquén, Neuquén",
        earth: "https://www.google.com/maps?q=Calle+San+Juan+3456,+Neuquén,+Neuquén",
        email: "neuquen@rollinghealth.com.ar",
        phone: "+54 299 901-2345",
        img: "/images/centrosmedicos/centro10.jpg",
        specialty: [
            "Alergia e Inmunología",
            "Cardiología",
            "Cirugía Plástica",
            "Consultorios Externos",
            "Cuidados Paliativos",
            "Endocrinología",
            "Gastroenterología y Endoscopías",
            "Ginecología",
            "Hemoterapia",
            "Infectología",
            "Laboratorio",
            "Neumonología",
            "Oftalmología Clínica y Quirúrgica",
            "Oncología",
            "Rehabilitación"
        ]
    },
    {
        name: "Centro Médico Rosario Salud",
        address: "Bv. Oroño 789, Rosario, Santa Fe",
        earth: "https://www.google.com/maps?q=Bv.+Oroño+789,+Rosario,+Santa+Fe",
        email: "rosario@rollinghealth.com.ar",
        phone: "+54 341 345-6789",
        img: "/images/centrosmedicos/centro11.jpg",
        specialty: [
            "Alergia e Inmunología",
            "Cardiología",
            "Cirugía",
            "Dermatología",
            "Ecografía y Ecodoppler",
            "Endocrinología",
            "Gastroenterología y Endoscopías",
            "Guardia Médica",
            "Laboratorio",
            "Neurología",
            "Odontología",
            "Oftalmología Clínica y Quirúrgica",
            "Oncología",
            "Reumatología",
            "Salud Mental"
        ]
    },
    {
        name: "Centro Médico Salta Salud",
        address: "Calle Mitre 5678, Salta, Salta",
        earth: "https://www.google.com/maps?q=Calle+Mitre+5678,+Salta,+Salta",
        email: "salta@rollinghealth.com.ar",
        phone: "+54 387 123-4567",
        img: "/images/centrosmedicos/centro12.jpg",
        specialty: [
            "Cardiología",
            "Clínica Médica - Medicina Interna",
            "Consultorios Externos",
            "Dermatología",
            "Diagnóstico por Imágenes",
            "Ecografía y Ecodoppler",
            "Endocrinología",
            "Ginecología",
            "Guardia Médica",
            "Hematología",
            "Infectología",
            "Laboratorio",
            "Oftalmología Clínica y Quirúrgica",
            "Otorrinolaringología",
            "Traumatología y Ortopedia"
        ]
    },
    {
        name: "Centro Médico San Juan Vida",
        address: "Av. Libertador 4567, San Juan, San Juan",
        earth: "https://www.google.com/maps?q=Av.+Libertador+4567,+San+Juan,+San+Juan",
        email: "sanjuan@rollinghealth.com.ar",
        phone: "+54 264 012-3456",
        img: "/images/centrosmedicos/centro13.jpg",
        specialty: [
            "Alergia e Inmunología",
            "Cardiología",
            "Cirugía Plástica",
            "Clínica Médica - Medicina Interna",
            "Dermatología",
            "Ecografía y Ecodoppler",
            "Gastroenterología y Endoscopías",
            "Guardia Médica",
            "Neurología",
            "Odontología",
            "Oftalmología Clínica y Quirúrgica",
            "Oncología",
            "Otorrinolaringología",
            "Traumatología y Ortopedia",
            "Urología"
        ]
    },
    {
        name: "Centro Médico Tierra del Fuego Salud",
        address: "Calle San Martín 9012, Ushuaia, Tierra del Fuego",
        earth: "https://www.google.com/maps?q=Calle+San+Martín+9012,+Ushuaia,+Tierra+del+Fuego",
        email: "tierradelfuego@rollinghealth.com.ar",
        phone: "+54 2901 567-8901",
        img: "/images/centrosmedicos/centro14.jpg",
        specialty: [
            "Alergia e Inmunología",
            "Cardiología",
            "Cirugía General",
            "Clínica Médica - Medicina Interna",
            "Dermatología",
            "Diagnóstico por Imágenes",
            "Endocrinología",
            "Ginecología",
            "Guardia Médica",
            "Laboratorio",
            "Neurología",
            "Odontología",
            "Oftalmología Clínica y Quirúrgica",
            "Oncología",
            "Traumatología y Ortopedia"
        ]
    },
    {
        name: "Centro Médico Tucumán Salud",
        address: "Av. Sarmiento 123, San Miguel de Tucumán, Tucumán",
        earth: "https://www.google.com/maps?q=Av.+Sarmiento+123,+San+Miguel+de+Tucumán,+Tucumán",
        email: "tucuman@rollinghealth.com.ar",
        phone: "+54 381 123-4567",
        img: "/images/centrosmedicos/centro15.jpg",
        specialty: [
            "Alergia e Inmunología",
            "Cardiología",
            "Cirugía Plástica",
            "Clínica Médica - Medicina Interna",
            "Dermatología",
            "Ecografía y Ecodoppler",
            "Endocrinología",
            "Gastroenterología y Endoscopías",
            "Ginecología",
            "Infectología",
            "Laboratorio",
            "Odontología",
            "Oftalmología Clínica y Quirúrgica",
            "Reumatología",
            "Traumatología y Ortopedia"
        ]
    }
];