export const medicos = [
    {
        name: "Dr. Juan Pérez",
        speciality: "Cardiología",
        mp: "1234",
        bio: "Dr. Juan Pérez es un cardiólogo con más de 15 años de experiencia en el tratamiento de enfermedades cardiovasculares.",
        centroMedico: "Centro Médico Bahía Blanca",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 291 890-1234 int. 101",
        email: "jperez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg1.jpg"
    },
    {
        name: "Dra. María González",
        speciality: "Cardiología",
        mp: "5678",
        bio: "Dra. María González es especialista en cardiología preventiva y rehabilitación cardiovascular.",
        centroMedico: "Centro Médico Bahía Blanca",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 291 890-1234 int. 102",
        email: "mgonzalez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg2.jpg"
    },
    {
        name: "Dr. Carlos López",
        speciality: "Dermatología",
        mp: "9101",
        bio: "Dr. Carlos López tiene una amplia experiencia en dermatología clínica y estética.",
        centroMedico: "Centro Médico Bahía Blanca",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 291 890-1234 int. 103",
        email: "clopez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg3.jpg"
    },
    {
        name: "Dra. Ana Rodríguez",
        speciality: "Dermatología",
        mp: "1121",
        bio: "Dra. Ana Rodríguez se especializa en tratamientos dermatológicos avanzados y cuidado de la piel.",
        centroMedico: "Centro Médico Bahía Blanca",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 291 890-1234 int. 104",
        email: "arodriguez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg4.jpg"
    },
    {
        name: "Dr. Pablo Gómez",
        speciality: "Endocrinología",
        mp: "3141",
        bio: "Dr. Pablo Gómez es un endocrinólogo con experiencia en el manejo de enfermedades hormonales.",
        centroMedico: "Centro Médico Bahía Blanca",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 291 890-1234 int. 105",
        email: "pgomez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg5.jpg"
    },
    {
        name: "Dra. Laura Díaz",
        speciality: "Endocrinología",
        mp: "5161",
        bio: "Dra. Laura Díaz es especialista en el tratamiento de trastornos endocrinos y metabólicos.",
        centroMedico: "Centro Médico Bahía Blanca",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 291 890-1234 int. 106",
        email: "ldiaz@rollinghealth.com.ar",
        img: "/images/medicos/medicimg6.jpg"
    },
    {
        name: "Dr. Andrés Torres",
        speciality: "Gastroenterología y Endoscopías",
        mp: "7181",
        bio: "Dr. Andrés Torres tiene más de 10 años de experiencia en gastroenterología y endoscopía.",
        centroMedico: "Centro Médico Bahía Blanca",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 291 890-1234 int. 107",
        email: "atorres@rollinghealth.com.ar",
        img: "/images/medicos/medicimg7.jpg"
    },
    {
        name: "Dra. Patricia Ramírez",
        speciality: "Gastroenterología y Endoscopías",
        mp: "9202",
        bio: "Dra. Patricia Ramírez es una experta en enfermedades digestivas y procedimientos endoscópicos.",
        centroMedico: "Centro Médico Bahía Blanca",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 291 890-1234 int. 108",
        email: "pramirez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg8.jpg"
    },
    {
        name: "Dr. Luis Fernández",
        speciality: "Ginecología",
        mp: "1223",
        bio: "Dr. Luis Fernández se especializa en salud reproductiva y cuidados ginecológicos.",
        centroMedico: "Centro Médico Bahía Blanca",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 291 890-1234 int. 109",
        email: "lfernandez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg9.jpg"
    },
    {
        name: "Dra. Sofía Martínez",
        speciality: "Ginecología",
        mp: "3243",
        bio: "Dra. Sofía Martínez tiene amplia experiencia en obstetricia y ginecología.",
        centroMedico: "Centro Médico Bahía Blanca",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 291 890-1234 int. 110",
        email: "smartinez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg10.jpg"
    },
    {
        name: "Dr. Javier Herrera",
        speciality: "Neurología",
        mp: "5264",
        bio: "Dr. Javier Herrera es un neurólogo con experiencia en trastornos neurológicos y enfermedades neurodegenerativas.",
        centroMedico: "Centro Médico Bahía Blanca",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 291 890-1234 int. 111",
        email: "jherrera@rollinghealth.com.ar",
        img: "/images/medicos/medicimg11.jpg"
    },
    {
        name: "Dra. Marta Ruiz",
        speciality: "Neurología",
        mp: "7284",
        bio: "Dra. Marta Ruiz se especializa en neurología infantil y epilepsia.",
        centroMedico: "Centro Médico Bahía Blanca",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 291 890-1234 int. 112",
        email: "mruiz@rollinghealth.com.ar",
        img: "/images/medicos/medicimg1.jpg"
    },
    {
        name: "Dr. Ricardo García",
        speciality: "Odontología",
        mp: "9305",
        bio: "Dr. Ricardo García es odontólogo con especialización en ortodoncia y estética dental.",
        centroMedico: "Centro Médico Bahía Blanca",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 291 890-1234 int. 113",
        email: "rgarcia@rollinghealth.com.ar",
        img: "/images/medicos/medicimg2.jpg"

    },
    {
        name: "Dra. Natalia Vargas",
        speciality: "Odontología",
        mp: "1345",
        bio: "Dra. Natalia Vargas se especializa en periodoncia y tratamiento de enfermedades de las encías.",
        centroMedico: "Centro Médico Bahía Blanca",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 291 890-1234 int. 114",
        email: "nvargas@rollinghealth.com.ar",
        img: "/images/medicos/medicimg3.jpg"
    },
    {
        name: "Dr. Manuel Castro",
        speciality: "Oncología",
        mp: "3365",
        bio: "Dr. Manuel Castro es oncólogo con más de 20 años de experiencia en el tratamiento de cáncer.",
        centroMedico: "Centro Médico Bahía Blanca",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 291 890-1234 int. 115",
        email: "mcastro@rollinghealth.com.ar",
        img: "/images/medicos/medicimg4.jpg"
    },
    {
        name: "Dr. Diego Almada",
        speciality: "Traumatología y Ortopedia",
        mp: "1475",
        bio: "Dr. Diego Almada se especializa en traumatología deportiva y cirugías de reconstrucción articular.",
        centroMedico: "Centro Médico Chaco Salud",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 294 890-1234 int. 101",
        email: "dalmada@rollinghealth.com.ar",
        img: "/images/medicos/medicimg5.jpg"
    },
    {
        name: "Dra. Laura Saavedra",
        speciality: "Traumatología y Ortopedia",
        mp: "2891",
        bio: "Dra. Laura Saavedra cuenta con experiencia en ortopedia pediátrica y tratamiento de fracturas complejas.",
        centroMedico: "Centro Médico Chaco Salud",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 294 890-1234 int. 102",
        email: "lsaavedra@rollinghealth.com.ar",
        img: "/images/medicos/medicimg6.jpg"
    },
    {
        name: "Dr. Emilio Cabrera",
        speciality: "Cirugía General",
        mp: "3610",
        bio: "Dr. Emilio Cabrera es especialista en cirugía laparoscópica y procedimientos mínimamente invasivos.",
        centroMedico: "Centro Médico Chaco Salud",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 294 890-1234 int. 103",
        email: "ecabrera@rollinghealth.com.ar",
        img: "/images/medicos/medicimg7.jpg"
    },
    {
        name: "Dra. Lucía Aguirre",
        speciality: "Cirugía General",
        mp: "4256",
        bio: "Dra. Lucía Aguirre es una cirujana general con experiencia en emergencias quirúrgicas y cirugía oncológica.",
        centroMedico: "Centro Médico Chaco Salud",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 294 890-1234 int. 104",
        email: "laguirre@rollinghealth.com.ar",
        img: "/images/medicos/medicimg8.jpg"
    },
    {
        name: "Dr. Daniel Marín",
        speciality: "Infectología",
        mp: "5324",
        bio: "Dr. Daniel Marín se especializa en el diagnóstico y tratamiento de enfermedades infecciosas.",
        centroMedico: "Centro Médico Chaco Salud",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 294 890-1234 int. 105",
        email: "dmarin@rollinghealth.com.ar",
        img: "/images/medicos/medicimg9.jpg"
    },
    {
        name: "Dra. Paula Navarro",
        speciality: "Infectología",
        mp: "6427",
        bio: "Dra. Paula Navarro es experta en el manejo de infecciones crónicas y enfermedades tropicales.",
        centroMedico: "Centro Médico Chaco Salud",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 294 890-1234 int. 106",
        email: "pnavarro@rollinghealth.com.ar",
        img: "/images/medicos/medicimg10.jpg"
    },
    {
        name: "Dr. Raúl Vega",
        speciality: "Neumonología",
        mp: "7893",
        bio: "Dr. Raúl Vega es neumonólogo con especialización en enfermedades respiratorias crónicas y cuidados críticos.",
        centroMedico: "Centro Médico Chaco Salud",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 294 890-1234 int. 107",
        email: "rvega@rollinghealth.com.ar",
        img: "/images/medicos/medicimg11.jpg"
    },
    {
        name: "Dra. Marina Ortiz",
        speciality: "Neumonología",
        mp: "8259",
        bio: "Dra. Marina Ortiz tiene experiencia en tratamiento de asma, EPOC y enfermedades intersticiales pulmonares.",
        centroMedico: "Centro Médico Chaco Salud",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 294 890-1234 int. 108",
        email: "mortiz@rollinghealth.com.ar",
        img: "/images/medicos/medicimg1.jpg"
    },
    {
        name: "Dr. Tomás Ruiz",
        speciality: "Neurología",
        mp: "9374",
        bio: "Dr. Tomás Ruiz se especializa en trastornos neurológicos y neurocirugía.",
        centroMedico: "Centro Médico Chaco Salud",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 294 890-1234 int. 109",
        email: "truiz@rollinghealth.com.ar",
        img: "/images/medicos/medicimg2.jpg"
    },
    {
        name: "Dra. Gabriela Castro",
        speciality: "Neurología",
        mp: "1058",
        bio: "Dra. Gabriela Castro cuenta con experiencia en neurología infantil y epilepsia.",
        centroMedico: "Centro Médico Chaco Salud",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 294 890-1234 int. 110",
        email: "gcastro@rollinghealth.com.ar",
        img: "/images/medicos/medicimg3.jpg"
    },
    {
        name: "Dr. Hernán Benítez",
        speciality: "Oncología",
        mp: "2736",
        bio: "Dr. Hernán Benítez es oncólogo con enfoque en terapias avanzadas y medicina personalizada.",
        centroMedico: "Centro Médico Chaco Salud",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 294 890-1234 int. 111",
        email: "hbenitez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg4.jpg"
    },
    {
        name: "Dra. Isabel Flores",
        speciality: "Oncología",
        mp: "3814",
        bio: "Dra. Isabel Flores se especializa en oncología ginecológica y cuidados paliativos.",
        centroMedico: "Centro Médico Chaco Salud",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 294 890-1234 int. 112",
        email: "iflores@rollinghealth.com.ar",
        img: "/images/medicos/medicimg5.jpg"
    },
    {
        name: "Dr. Martín Muñoz",
        speciality: "Traumatología y Ortopedia",
        mp: "4937",
        bio: "Dr. Martín Muñoz se dedica a la traumatología pediátrica y cirugía ortopédica.",
        centroMedico: "Centro Médico Chaco Salud",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 294 890-1234 int. 113",
        email: "mmunoz@rollinghealth.com.ar",
        img: "/images/medicos/medicimg6.jpg"
    },
    {
        name: "Dra. Alejandra Prieto",
        speciality: "Traumatología y Ortopedia",
        mp: "5739",
        bio: "Dra. Alejandra Prieto tiene experiencia en tratamiento de lesiones deportivas y fracturas.",
        centroMedico: "Centro Médico Chaco Salud",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 294 890-1234 int. 114",
        email: "aprieto@rollinghealth.com.ar",
        img: "/images/medicos/medicimg7.jpg"
    },
    {
        name: "Dr. Enrique Duarte",
        speciality: "Urología",
        mp: "6721",
        bio: "Dr. Enrique Duarte se especializa en cirugía urológica y tratamiento de enfermedades del tracto urinario.",
        centroMedico: "Centro Médico Chaco Salud",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 294 890-1234 int. 115",
        email: "eduarte@rollinghealth.com.ar",
        img: "/images/medicos/medicimg8.jpg"
    },
    {
        name: "Dr. Andrés Moreno",
        speciality: "Alergia e Inmunología",
        mp: "1278",
        bio: "Dr. Andrés Moreno es especialista en alergias y enfermedades inmunológicas con más de 12 años de experiencia.",
        centroMedico: "Centro Médico Capital Bienestar",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 11 890-1234 int. 101",
        email: "amoreno@rollinghealth.com.ar",
        img: "/images/medicos/medicimg9.jpg"
    },
    {
        name: "Dra. Valeria Santos",
        speciality: "Alergia e Inmunología",
        mp: "2396",
        bio: "Dra. Valeria Santos cuenta con experiencia en tratamiento de alergias y trastornos inmunológicos en niños y adultos.",
        centroMedico: "Centro Médico Capital Bienestar",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 11 890-1234 int. 102",
        email: "vsantos@rollinghealth.com.ar",
        img: "/images/medicos/medicimg10.jpg"
    },
    {
        name: "Dr. Federico Blanco",
        speciality: "Cardiología",
        mp: "3489",
        bio: "Dr. Federico Blanco es cardiólogo especializado en prevención y rehabilitación cardiovascular.",
        centroMedico: "Centro Médico Capital Bienestar",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 11 890-1234 int. 103",
        email: "fblanco@rollinghealth.com.ar",
        img: "/images/medicos/medicimg11.jpg"
    },
    {
        name: "Dra. Lucía Vargas",
        speciality: "Cardiología",
        mp: "4512",
        bio: "Dra. Lucía Vargas tiene experiencia en el manejo de enfermedades cardiovasculares y arritmias.",
        centroMedico: "Centro Médico Capital Bienestar",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 11 890-1234 int. 104",
        email: "lvargas@rollinghealth.com.ar",
        img: "/images/medicos/medicimg1.jpg"
    },
    {
        name: "Dr. Javier Castro",
        speciality: "Dermatología",
        mp: "5784",
        bio: "Dr. Javier Castro es dermatólogo con especialización en tratamientos estéticos y enfermedades de la piel.",
        centroMedico: "Centro Médico Capital Bienestar",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 11 890-1234 int. 105",
        email: "jcastro@rollinghealth.com.ar",
        img: "/images/medicos/medicimg2.jpg"
    },
    {
        name: "Dra. María López",
        speciality: "Dermatología",
        mp: "6872",
        bio: "Dra. María López se dedica a la dermatología clínica y quirúrgica, con enfoque en cáncer de piel.",
        centroMedico: "Centro Médico Capital Bienestar",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 11 890-1234 int. 106",
        email: "mlopez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg3.jpg"
    },
    {
        name: "Dr. Roberto Ramírez",
        speciality: "Endocrinología",
        mp: "7934",
        bio: "Dr. Roberto Ramírez es endocrinólogo con experiencia en el tratamiento de diabetes y enfermedades tiroideas.",
        centroMedico: "Centro Médico Capital Bienestar",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 11 890-1234 int. 107",
        email: "rramirez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg4.jpg"
    },
    {
        name: "Dra. Sandra Herrera",
        speciality: "Endocrinología",
        mp: "8721",
        bio: "Dra. Sandra Herrera se especializa en endocrinología reproductiva y trastornos hormonales.",
        centroMedico: "Centro Médico Capital Bienestar",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 11 890-1234 int. 108",
        email: "sherrera@rollinghealth.com.ar",
        img: "/images/medicos/medicimg5.jpg"
    },
    {
        name: "Dr. Fernando Quiroga",
        speciality: "Gastroenterología y Endoscopías",
        mp: "9345",
        bio: "Dr. Fernando Quiroga es gastroenterólogo especializado en endoscopías y enfermedades del aparato digestivo.",
        centroMedico: "Centro Médico Capital Bienestar",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 11 890-1234 int. 109",
        email: "fquiroga@rollinghealth.com.ar",
        img: "/images/medicos/medicimg6.jpg"
    },
    {
        name: "Dra. Claudia Sánchez",
        speciality: "Gastroenterología y Endoscopías",
        mp: "1028",
        bio: "Dra. Claudia Sánchez tiene experiencia en endoscopías y tratamiento de enfermedades hepáticas.",
        centroMedico: "Centro Médico Capital Bienestar",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 11 890-1234 int. 110",
        email: "csanchez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg7.jpg"
    },
    {
        name: "Dr. Alejandro Díaz",
        speciality: "Ginecología",
        mp: "1143",
        bio: "Dr. Alejandro Díaz es ginecólogo con especialización en salud reproductiva y cuidados prenatales.",
        centroMedico: "Centro Médico Capital Bienestar",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 11 890-1234 int. 111",
        email: "adiaz@rollinghealth.com.ar",
        img: "/images/medicos/medicimg8.jpg"
    },
    {
        name: "Dra. Patricia Herrera",
        speciality: "Ginecología",
        mp: "1294",
        bio: "Dra. Patricia Herrera se especializa en ginecología oncológica y cirugía mínimamente invasiva.",
        centroMedico: "Centro Médico Capital Bienestar",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 11 890-1234 int. 112",
        email: "pherrera@rollinghealth.com.ar",
        img: "/images/medicos/medicimg9.jpg"
    },
    {
        name: "Dr. Marcelo Ruiz",
        speciality: "Neurología",
        mp: "2345",
        bio: "Dr. Marcelo Ruiz es neurólogo con experiencia en trastornos del sueño y enfermedades neurodegenerativas.",
        centroMedico: "Centro Médico Capital Bienestar",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 11 890-1234 int. 113",
        email: "mruiz@rollinghealth.com.ar",
        img: "/images/medicos/medicimg10.jpg"
    },
    {
        name: "Dra. Verónica Ortiz",
        speciality: "Neurología",
        mp: "3456",
        bio: "Dra. Verónica Ortiz se dedica a la neurología infantil y tratamiento de epilepsia.",
        centroMedico: "Centro Médico Capital Bienestar",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 11 890-1234 int. 114",
        email: "vortiz@rollinghealth.com.ar",
        img: "/images/medicos/medicimg11.jpg"
    },
    {
        name: "Dr. Héctor Gómez",
        speciality: "Odontología",
        mp: "4567",
        bio: "Dr. Héctor Gómez es odontólogo con especialización en implantología y estética dental.",
        centroMedico: "Centro Médico Capital Bienestar",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 11 890-1234 int. 115",
        email: "hgomez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg1.jpg"
    },
    {
        name: "Dr. Antonio Fernández",
        speciality: "Cardiología",
        mp: "1378",
        bio: "Dr. Antonio Fernández es especialista en cardiología clínica y tratamiento de enfermedades coronarias.",
        centroMedico: "Centro Médico Córdoba Vida",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 351 890-1234 int. 101",
        email: "afernandez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg2.jpg"
    },
    {
        name: "Dra. Isabel Molina",
        speciality: "Cardiología",
        mp: "2589",
        bio: "Dra. Isabel Molina se especializa en cardiología intervencionista y rehabilitación cardiovascular.",
        centroMedico: "Centro Médico Córdoba Vida",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 351 890-1234 int. 102",
        email: "imolina@rollinghealth.com.ar",
        img: "/images/medicos/medicimg3.jpg"
    },
    {
        name: "Dr. Javier Ramos",
        speciality: "Dermatología",
        mp: "3781",
        bio: "Dr. Javier Ramos es dermatólogo con experiencia en tratamientos de acné y enfermedades de la piel.",
        centroMedico: "Centro Médico Córdoba Vida",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 351 890-1234 int. 103",
        email: "jramos@rollinghealth.com.ar",
        img: "/images/medicos/medicimg4.jpg"
    },
    {
        name: "Dra. Camila Flores",
        speciality: "Dermatología",
        mp: "4894",
        bio: "Dra. Camila Flores se especializa en dermatología estética y cirugía dermatológica.",
        centroMedico: "Centro Médico Córdoba Vida",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 351 890-1234 int. 104",
        email: "cflores@rollinghealth.com.ar",
        img: "/images/medicos/medicimg5.jpg"
    },
    {
        name: "Dr. Alejandro Márquez",
        speciality: "Endocrinología",
        mp: "5783",
        bio: "Dr. Alejandro Márquez es endocrinólogo con especialización en diabetes y enfermedades tiroideas.",
        centroMedico: "Centro Médico Córdoba Vida",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 351 890-1234 int. 105",
        email: "amarquez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg6.jpg"
    },
    {
        name: "Dra. Carla Gutiérrez",
        speciality: "Endocrinología",
        mp: "6895",
        bio: "Dra. Carla Gutiérrez se dedica al tratamiento de trastornos hormonales y metabólicos.",
        centroMedico: "Centro Médico Córdoba Vida",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 351 890-1234 int. 106",
        email: "cgutierrez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg7.jpg"
    },
    {
        name: "Dr. Martín Sosa",
        speciality: "Gastroenterología y Endoscopías",
        mp: "7984",
        bio: "Dr. Martín Sosa es especialista en gastroenterología y endoscopías digestivas.",
        centroMedico: "Centro Médico Córdoba Vida",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 351 890-1234 int. 107",
        email: "msosa@rollinghealth.com.ar",
        img: "/images/medicos/medicimg8.jpg"
    },
    {
        name: "Dra. Mariana Castro",
        speciality: "Gastroenterología y Endoscopías",
        mp: "8239",
        bio: "Dra. Mariana Castro se especializa en enfermedades hepáticas y endoscopías terapéuticas.",
        centroMedico: "Centro Médico Córdoba Vida",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 351 890-1234 int. 108",
        email: "mcastro@rollinghealth.com.ar",
        img: "/images/medicos/medicimg9.jpg"
    },
    {
        name: "Dr. Ricardo Pérez",
        speciality: "Ginecología",
        mp: "9342",
        bio: "Dr. Ricardo Pérez es ginecólogo especializado en salud reproductiva y cirugía ginecológica.",
        centroMedico: "Centro Médico Córdoba Vida",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 351 890-1234 int. 109",
        email: "rperez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg10.jpg"
    },
    {
        name: "Dra. Laura Muñoz",
        speciality: "Ginecología",
        mp: "1024",
        bio: "Dra. Laura Muñoz se especializa en ginecología oncológica y medicina fetal.",
        centroMedico: "Centro Médico Córdoba Vida",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 351 890-1234 int. 110",
        email: "lmunoz@rollinghealth.com.ar",
        img: "/images/medicos/medicimg11.jpg"
    },
    {
        name: "Dr. Diego Herrera",
        speciality: "Neonatología",
        mp: "2135",
        bio: "Dr. Diego Herrera es especialista en neonatología y cuidados intensivos neonatales.",
        centroMedico: "Centro Médico Córdoba Vida",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 351 890-1234 int. 111",
        email: "dherrera@rollinghealth.com.ar",
        img: "/images/medicos/medicimg1.jpg"
    },
    {
        name: "Dra. Alicia Pérez",
        speciality: "Neonatología",
        mp: "3248",
        bio: "Dra. Alicia Pérez tiene experiencia en cuidados intensivos neonatales y seguimiento de bebés prematuros.",
        centroMedico: "Centro Médico Córdoba Vida",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 351 890-1234 int. 112",
        email: "aperez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg2.jpg"
    },
    {
        name: "Dr. Enrique Sánchez",
        speciality: "Neurología",
        mp: "4312",
        bio: "Dr. Enrique Sánchez es neurólogo especializado en enfermedades neurodegenerativas y trastornos del movimiento.",
        centroMedico: "Centro Médico Córdoba Vida",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 351 890-1234 int. 113",
        email: "esanchez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg3.jpg"
    },
    {
        name: "Dra. Victoria González",
        speciality: "Neurología",
        mp: "5423",
        bio: "Dra. Victoria González se dedica a la neurología pediátrica y tratamiento de epilepsia.",
        centroMedico: "Centro Médico Córdoba Vida",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 351 890-1234 int. 114",
        email: "vgonzalez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg4.jpg"
    },
    {
        name: "Dr. Alejandro López",
        speciality: "Neumonología",
        mp: "6478",
        bio: "Dr. Alejandro López es neumonólogo especializado en enfermedades respiratorias crónicas.",
        centroMedico: "Centro Médico Córdoba Vida",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 351 890-1234 int. 115",
        email: "alopez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg5.jpg"
    },
    {
        name: "Dr. Carlos Mendoza",
        speciality: "Cardiología",
        mp: "4756",
        bio: "Dr. Carlos Mendoza es cardiólogo especializado en enfermedades coronarias y rehabilitación cardiovascular.",
        centroMedico: "Centro Médico Tucumán Salud",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 381 890-1234 int. 101",
        email: "cmendoza@rollinghealth.com.ar",
        img: "/images/medicos/medicimg6.jpg"
    },
    {
        name: "Dra. Ana Ríos",
        speciality: "Cardiología",
        mp: "5874",
        bio: "Dra. Ana Ríos se dedica a la cardiología preventiva y tratamiento de hipertensión.",
        centroMedico: "Centro Médico Tucumán Salud",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 381 890-1234 int. 102",
        email: "arios@rollinghealth.com.ar",
        img: "/images/medicos/medicimg7.jpg"
    },
    {
        name: "Dr. Felipe Gómez",
        speciality: "Dermatología",
        mp: "6123",
        bio: "Dr. Felipe Gómez es dermatólogo con experiencia en tratamientos de psoriasis y dermatitis.",
        centroMedico: "Centro Médico Tucumán Salud",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 381 890-1234 int. 103",
        email: "fgomez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg8.jpg"
    },
    {
        name: "Dra. Laura Figueroa",
        speciality: "Dermatología",
        mp: "7351",
        bio: "Dra. Laura Figueroa se especializa en dermatología estética y tratamientos de rejuvenecimiento.",
        centroMedico: "Centro Médico Tucumán Salud",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 381 890-1234 int. 104",
        email: "lfigueroa@rollinghealth.com.ar",
        img: "/images/medicos/medicimg9.jpg"
    },
    {
        name: "Dr. Santiago López",
        speciality: "Endocrinología",
        mp: "8452",
        bio: "Dr. Santiago López es endocrinólogo especializado en diabetes y trastornos metabólicos.",
        centroMedico: "Centro Médico Tucumán Salud",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 381 890-1234 int. 105",
        email: "slopez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg10.jpg"
    },
    {
        name: "Dra. Marta Ruiz",
        speciality: "Endocrinología",
        mp: "9643",
        bio: "Dra. Marta Ruiz se dedica al tratamiento de enfermedades tiroideas y hormonales.",
        centroMedico: "Centro Médico Tucumán Salud",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 381 890-1234 int. 106",
        email: "mruiz@rollinghealth.com.ar",
        img: "/images/medicos/medicimg11.jpg"
    },
    {
        name: "Dr. Pablo García",
        speciality: "Gastroenterología y Endoscopías",
        mp: "1278",
        bio: "Dr. Pablo García es gastroenterólogo especializado en endoscopías y enfermedades digestivas.",
        centroMedico: "Centro Médico Tucumán Salud",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 381 890-1234 int. 107",
        email: "pgarcia@rollinghealth.com.ar",
        img: "/images/medicos/medicimg1.jpg"
    },
    {
        name: "Dra. Silvia Martínez",
        speciality: "Gastroenterología y Endoscopías",
        mp: "2379",
        bio: "Dra. Silvia Martínez se especializa en tratamiento de enfermedades hepáticas y endoscopías terapéuticas.",
        centroMedico: "Centro Médico Tucumán Salud",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 381 890-1234 int. 108",
        email: "smartinez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg2.jpg"
    },
    {
        name: "Dr. Lucas Pérez",
        speciality: "Ginecología",
        mp: "3456",
        bio: "Dr. Lucas Pérez es ginecólogo con especialización en salud reproductiva y cirugía ginecológica.",
        centroMedico: "Centro Médico Tucumán Salud",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 381 890-1234 int. 109",
        email: "lperez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg3.jpg"
    },
    {
        name: "Dra. Patricia Gómez",
        speciality: "Ginecología",
        mp: "4567",
        bio: "Dra. Patricia Gómez se especializa en ginecología oncológica y medicina fetal.",
        centroMedico: "Centro Médico Tucumán Salud",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 381 890-1234 int. 110",
        email: "pgomez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg4.jpg"
    },
    {
        name: "Dr. Javier Romero",
        speciality: "Neurología",
        mp: "5678",
        bio: "Dr. Javier Romero es neurólogo con experiencia en enfermedades neurodegenerativas y trastornos del sueño.",
        centroMedico: "Centro Médico Tucumán Salud",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 381 890-1234 int. 111",
        email: "jromero@rollinghealth.com.ar",
        img: "/images/medicos/medicimg5.jpg"
    },
    {
        name: "Dra. Sofía Álvarez",
        speciality: "Neurología",
        mp: "6789",
        bio: "Dra. Sofía Álvarez se dedica a la neurología pediátrica y tratamiento de epilepsia.",
        centroMedico: "Centro Médico Tucumán Salud",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 381 890-1234 int. 112",
        email: "salvarez@rollinghealth.com.ar",
        img: "/images/medicos/medicimg6.jpg"
    },
    {
        name: "Dr. Marcos Torres",
        speciality: "Odontología",
        mp: "7890",
        bio: "Dr. Marcos Torres es odontólogo especializado en implantología y estética dental.",
        centroMedico: "Centro Médico Tucumán Salud",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 381 890-1234 int. 113",
        email: "mtorres@rollinghealth.com.ar",
        img: "/images/medicos/medicimg7.jpg"
    },
    {
        name: "Dra. Verónica Luna",
        speciality: "Odontología",
        mp: "8901",
        bio: "Dra. Verónica Luna se especializa en ortodoncia y tratamientos de maloclusiones dentales.",
        centroMedico: "Centro Médico Tucumán Salud",
        atencion: "tarde 16:00 a 21:00",
        phone: "+54 381 890-1234 int. 114",
        email: "vluna@rollinghealth.com.ar",
        img: "/images/medicos/medicimg8.jpg"
    },
    {
        name: "Dr. Fernando Herrera",
        speciality: "Traumatología y Ortopedia",
        mp: "9012",
        bio: "Dr. Fernando Herrera es traumatólogo con experiencia en cirugías ortopédicas y tratamiento de fracturas.",
        centroMedico: "Centro Médico Tucumán Salud",
        atencion: "mañana de 8:00 a 13:00 hs",
        phone: "+54 381 890-1234 int. 115",
        email: "fherrera@rollinghealth.com.ar",
        img: "/images/medicos/medicimg9.jpg"
    }
];