export const slidesData = [
    {
        id: 2,
        title: "Más de 10 Centros de Atención Médica en el país",
        text: "En nuestros centros multidisciplinarios, ofrecemos atención cercana y accesible en toda Argentina.",
        img: "/images/slidehome/slide_img-2.jpg",
        button: "Descubre Más",
        link: "/centros",
    },
    {
        id: 1,
        title: "Brindamos un servicio de salud integral con excelencia",
        text: "Nuestros servicios de salud integral te garantizan atención de calidad y bienestar en cada visita.",
        img: "/images/slidehome/slide_img-1.jpg",
        button: "Conocer Coberturas",
        link: "/login",
    },
    {
        id: 3,
        title: "Un plantel profesional mejor preparado para tu salud",
        text: "Nuestro equipo de profesionales altamente capacitados está comprometido con tu salud y bienestar diario.",
        img: "/images/slidehome/slide_img-3.jpg",
        button: "Ver Equipo",
        link: "/staff",
    },
    {
        id: 4,
        title: "Asistencia médica profesional inmediata las 24 horas ",
        text: "Un equipo médico con formación continua y dedicación para brindarte la mejor atención posible al instante.",
        img: "/images/slidehome/slide_img-4.jpg",
        button: "Comunícate ahora",
        icon: "whatsapp",
        link: "/nosotros",
    },
]